"""FastAPI application — M6 /chat endpoint (plan section 6).

Exposes the Gaffer agent over HTTP:

POST /chat
    body: { "message": str, "session_id": str }
    Returns the structured AgentAnswer as JSON with fully-qualified visual URLs:
    {
        "answer_text": str,
        "visuals":    [url, ...],          # absolute, browser-fetchable
        "cited_stats": [{"label", "value", "source"}, ...],
        "grounded":   bool,                # M5 audit flag
        "verification_notes": [str, ...],  # M5 audit trail
    }

GET /health
    Returns { "status": "ok", "competition": "...", ... }

Static PNGs generated by the analysis tools are served from /static/* (mounted
from backend/app/static/). Visual URLs in the AgentAnswer are relative paths
(/static/shot_maps/...) that are absolutized here using PUBLIC_BASE_URL before
being returned to the client.

Session memory is an in-memory dict keyed by session_id that holds the last
MAX_HISTORY_TURNS user/assistant turn pairs as context for follow-up questions.
This resets on server restart; SQLite persistence is v2.

CORS: Vite dev origin (http://localhost:5173) is always allowed; additional
origins can be added via the CORS_ORIGINS env var (comma-separated).

Environment variables:
    PUBLIC_BASE_URL      default http://localhost:8000
    CORS_ORIGINS         comma-separated extra allowed origins (optional)
"""

from __future__ import annotations

import logging
import os
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from .agent.graph import run
from .data.ingest import COMPETITION_ID, SEASON_ID
from .viz.pitch import STATIC_DIR

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_PUBLIC_BASE_URL: str = os.getenv("PUBLIC_BASE_URL", "http://localhost:8000").rstrip("/")

# CORS: always allow common Vite dev origins (localhost + 127.0.0.1); extras via env.
_CORS_ORIGINS: list[str] = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
_extra = os.getenv("CORS_ORIGINS", "")
if _extra:
    _CORS_ORIGINS += [o.strip() for o in _extra.split(",") if o.strip()]

# Session history: in-memory dict, keyed by session_id.
# Each entry is a flat list of {role, content} pairs (user + assistant interleaved).
# v1 only — resets on server restart; SQLite persistence is a v2 task.
_SESSIONS: dict[str, list[dict[str, str]]] = {}
_MAX_HISTORY_TURNS: int = 6  # 6 turns = 12 messages

# Static root is backend/app/static (parent of the shot_maps sub-dir).
_STATIC_ROOT = STATIC_DIR.parent
_STATIC_ROOT.mkdir(parents=True, exist_ok=True)  # ensure all sub-dirs exist on startup

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(title="Gaffer", version="0.2.0", description="Conversational football analyst")

app.add_middleware(
    CORSMiddleware,
    allow_origins=_CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.mount("/static", StaticFiles(directory=str(_STATIC_ROOT)), name="static")


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    message: str
    session_id: str = "default"


class CitedStatOut(BaseModel):
    label: str
    value: str
    source: str


class ChatResponse(BaseModel):
    answer_text: str
    visuals: list[str]
    cited_stats: list[CitedStatOut]
    grounded: bool
    verification_notes: list[str]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _absolutize(url: str) -> str:
    """Convert a served-relative URL like /static/... to a full browser-fetchable URL."""
    if url.startswith("/"):
        return f"{_PUBLIC_BASE_URL}{url}"
    return url  # already absolute


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@app.get("/health")
def health() -> dict[str, Any]:
    """Liveness check — also exposes the loaded competition for diagnostics."""
    return {
        "status": "ok",
        "competition": "FIFA World Cup 2022",
        "competition_id": COMPETITION_ID,
        "season_id": SEASON_ID,
    }


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest) -> ChatResponse:
    """Run the agent on ``message`` and return a grounded structured answer.

    The response always includes ``grounded`` and ``verification_notes`` so the
    frontend (M7) can render the grounded / corrected badge without any
    post-processing.
    """
    # Retrieve and trim session history to last N turns (user+assistant pairs).
    history = _SESSIONS.get(req.session_id, [])
    trimmed = history[-(2 * _MAX_HISTORY_TURNS):]

    try:
        answer = run(req.message, history=trimmed if trimmed else None)
    except Exception as exc:
        logger.exception("Agent failed for session %s", req.session_id)
        raise HTTPException(status_code=500, detail=f"Agent error: {exc}") from exc

    # Absolutize visual URLs before returning — they are relative (/static/...)
    # from the tools layer; the client needs fully-qualified URLs.
    abs_visuals = [_absolutize(v) for v in answer.visuals]

    # Persist this turn for follow-up questions.
    updated = list(history) + [
        {"role": "user", "content": req.message},
        {"role": "assistant", "content": answer.answer_text},
    ]
    _SESSIONS[req.session_id] = updated[-(2 * _MAX_HISTORY_TURNS):]

    return ChatResponse(
        answer_text=answer.answer_text,
        visuals=abs_visuals,
        cited_stats=[
            CitedStatOut(label=s.label, value=s.value, source=s.source)
            for s in answer.cited_stats
        ],
        grounded=answer.grounded,
        verification_notes=answer.verification_notes,
    )
