// Frontend data layer. Shot markers + match stats come from real StatsBomb
// event data (WC 2022 final, Argentina vs France), generated by
// backend/scripts/gen_shotmap.py into shotmap.generated.json — not hand-authored.
import generated from "./shotmap.generated.json";

export type Role = "user" | "gaffer";

export interface Message {
  role: Role;
  label: string;
  showDot: boolean;
  text: string;
}

export interface ExamplePrompt {
  text: string;
}

export const EXAMPLE_PROMPTS: ExamplePrompt[] = [
  { text: "Compare Ronaldo and Messi's shot maps" },
  { text: "How did the winners break a low block?" },
  { text: "Map Argentina's progressive passes into the final third" },
  { text: "Where was France most vulnerable in transition?" },
];

// Canned analyst reply used for any freshly-sent question in the demo.
export const GAFFER_REPLY =
  "Mapped it on the board. The shape of the data is consistent — most of the value " +
  "concentrates in the right half-space, while the rest are low-percentage attempts " +
  "from distance. One high-xG chance is what separated the sides.";

// One real shot, in design SVG space, with the StatsBomb facts behind it.
export interface RawShot {
  cx: number;
  cy: number;
  xg: number;
  goal: boolean;
  player: string;
  team: string;
  minute: number;
  outcome: string;
}

// A RawShot plus the rendered marker geometry/style.
export interface ShotMarker extends RawShot {
  r: number;
  fill: string;
  stroke: string;
  strokeWidth: number;
  fillOpacity: number;
  strokeOpacity: number;
}

export const ACCENT = "#34d399"; // subject team (Argentina)
export const AMBER = "#e8a13a"; // opponent (France)

// Marker styling translated 1:1 from the design export's `mk()` helper.
function toMarkers(arr: RawShot[], color: string): ShotMarker[] {
  return arr.map((d) => ({
    ...d,
    r: 5 + d.xg * 20,
    fill: d.goal ? color : "none",
    stroke: color,
    strokeWidth: d.goal ? 1 : 2.5,
    fillOpacity: d.goal ? Math.min(0.92, 0.45 + d.xg * 0.55) : 0,
    strokeOpacity: d.goal ? 0.9 : 0.7,
  }));
}

export function buildShots(showOpponent = true): ShotMarker[] {
  return toMarkers(generated.shots.subject as RawShot[], ACCENT).concat(
    showOpponent
      ? toMarkers(generated.shots.opponent as RawShot[], AMBER)
      : [],
  );
}

// Real match facts derived from the StatsBomb cache (see generator above).
export const COMPETITION = generated.competition;
export const MATCH = {
  home: generated.home,
  away: generated.away,
  subject: generated.subject,
  opponent: generated.opponent,
};
export const STATS = generated.stats;
export const TOP_CHANCE = generated.topChance;

// Raw per-shot data (design SVG space) for inline previews like the mini map.
export const SUBJECT_SHOTS = generated.shots.subject as RawShot[];
export const OPPONENT_SHOTS = generated.shots.opponent as RawShot[];
